### ISSUE TITLE
License questions

### ISSUE THREAD

**Issue by gundalow** [Infinidat/ansible-infinidat-collection#1]
Hi,
It's great to see you've created a collection for the Infinidat content, thank you.

The original modules from Ansible were GPLv3+ and the module_utils were GPLv3+/BSD.

I can see that you've set the Apache license in the root of the repo, and also in every file, ie https://github.com/Infinidat/ansible-infinidat-collection/blob/develop/plugins/modules/infini_export.py#L4

If we look at the original for the above file https://github.com/ansible/ansible/blob/pre-ansible-base/lib/ansible/modules/storage/infinidat/infini_export.py we can see that 7 people have contributed to this.

You can't relicense without getting sign off from all contributors to all files, please speak to your legal team for further advice.

**Comment by anshulbehl** [comment]
@sqqqrly  Can you check and comment on this?

**Comment by gundalow** [comment]
@sqqqrly @ekaulberg thank you in advance for looking into this.

Friday 10th July is the deadline to get content moved out of `community.general` if you want it to be included in the Ansible 2.10 release.

**Comment by ekaulberg** [comment]
Hi @gundalow and @anshulbehl. Thanks for looping me in. As @sqqqrly is OOO/offline for the next week and a half, I'll try to get this addressed in his absence, but realistically may not be able to close all the open switches before Friday.

**Comment by sqqqrly** [comment]
Hi @gundalow and @anshulbehl.   I just saw this. This will be fixed this morning.

**Comment by gundalow** [comment]
@sqqqrly That's great, thank you.

I believe the following needs addressing so this collection can be included in `ansible 2.10`:

- [ ] Address this issue (#1)
- [ ] Publish collection to Galaxy
- [ ] https://github.com/ansible-collections/community.general/pull/607 to be merged
- [ ] PR against ansible-base (ansible/ansible) to update `lib/ansible/config/routing.yml` (once merged this needs backporting to `ansible/ansible:stable-2.10`

**Comment by thedoubl3j** [comment]
@gundalow it is on galaxy, found here: https://galaxy.ansible.com/infinidat/infinibox

**Comment by sqqqrly** [comment]
The license has been reverted back to GPL.  The collection was re-built and pushed as version 1.2.3 at https://galaxy.ansible.com/infinidat/infinibox.  The change was tagged as v1.2.3.

**Comment by felixfontein** [comment]
I just checked some of the files. It looks like you removed the original copyright statement by the orignal author:
```
# Copyright: (c) 2016, Gregory Shulov <gregory.shulov@gmail.com>
```
and replaced it with
```
# Copyright: (c) 2020, Infinidat <info@infinidat.com>
```
I'm not sure this is legal.

**Comment by ekaulberg** [comment]
Hi @felixfontein and @gundalow - original author Gregory Shulov was an Infinidat employee doing this as part of his work activities. He was subject to a standard assignment clause in his employment agreement, so the copyright really rests with Infinidat already. The copyright line should have been written for Infinidat originally but we didn't have much of a process to ensure that at the time of authorship.

**Comment by sqqqrly** [comment]
Licensing addressed.
