### ISSUE TITLE
Add filter documentation

### ISSUE THREAD

**Issue by samccann** [Infinidat/ansible-infinidat-collection#17]
ansible-core 2.14 adds 'side car docs' which gives collection owners the ability to add documentation for previously undocumentable filter and test plugins.

This requires creating yaml files in the same directory as the filter or test plugin code, one yaml file per plugin.

See https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/b64decode.yml for an example.

The following  filter needs docs:

https://docs.ansible.com/ansible/devel/collections/infinidat/infinibox/delta_time_filter.html#ansible-collections-infinidat-infinibox-delta-time-filter

Related to https://github.com/ansible-community/community-team/issues/65

**Comment by sqqqrly** [comment]
@samccann Thanks for your input.  This has been implemented.  Waiting for approval from AAH before closing.

https://github.com/Infinidat/ansible-infinidat-collection/blob/develop/plugins/filter/delta_time.yml

**Comment by samccann** [comment]
great thanks @sqqqrly !!
