### ISSUE TITLE
infini_map does not support mapping a volume to infinibox cluster

### ISSUE THREAD

**Issue by durai-sdm** [Infinidat/ansible-infinidat-collection#6]
Hi Team,

I'm working with one of our customer to provide ansible playbooks for infinibox provision activities. During testing we noticed map works only with hosts and not clusters.

I reviewed the code as well, for map its set to validate only hosts and not cluster due which below is error is logged. 

Below is the log.

[root@HYDNETAPPENGINE infinidat]# ansible-playbook infini_map.yml --e '{"host": "ansi_cluster", "volume":"ansi_vol4","system":"xx.xx.xx.xx"}' -v
Using /root/.ansible.cfg as config file
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Infinibox volume map] ********************************************************************************************************************************************

TASK [map volume] ******************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Host ansi_cluster not found"}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by sqqqrly** [comment]
Hello @durai-sdm,

There is a new release that addresses this.  See version 1.3.0 available from https://galaxy.ansible.com/infinidat/infinibox.

Please give this a try and see if it meets your needs.  There are examples in the infini_map module.  The upshot for use is that there is now a cluster parameter available along with the host parameter.   You must specify one or the other, but not both.
